name = "wrangler-scf-voting"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "8d06a01e958a084add5fcf155430e0fa"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "PROJECTS", class_name = "DurableProjects" } 
]