name = "wrangler-scf-voting"
main = "src/index.ts"
compatibility_date = "2022-06-05"

[durable_objects]
bindings = [
  { name = "FUND", class_name = "Fund" } 
]

[[migrations]]
tag = "v1"
new_classes = ["Fund"]

# [secrets]
# BOT_TOKEN
# WEBFLOW_API_KEY